drop table ex1_artist;
create table ex1_artist(id int, name varchar);
insert into ex1_artist values (1, 'tilt-six');
insert into ex1_artist values (2, 'ここなつ');
insert into ex1_artist values (3, 'DECO*27');
insert into ex1_artist values (4, '東雲夏陽 meets 日向美ビタースイーツ');
insert into ex1_artist values (5, 'Junky(GJBox)');
insert into ex1_artist values (6, '東雲心菜 meets 日向美ビタースイーツ');
insert into ex1_artist values (7, '角野寿和');
insert into ex1_artist values (8, 'Claris');
insert into ex1_artist values (9, 'kz(livetune)');
insert into ex1_artist values (10, '片岡健太');
insert into ex1_artist values (11, 'sumika');
